<?php
include_once "Resizeable.php";
include_once "Rectangle.php";

class Square extends Rectangle implements Resizeable
{
    public $edge;

    public function __construct($width, $height)
    {
        parent::__construct($width, $height);
    }

    /**
     * @return mixed
     */
    public function getEdge()
    {
        return $this->edge;
    }

    public function area()
    {
        return parent::area();
    }

    public function resize()
    {
        return parent::resize(); // TODO: Change the autogenerated stub
    }
}