<?php
include_once "Resizeable.php";
include_once "Rectangle.php";
include_once "Shape.php";


class Square extends Rectangle implements Resizeable
{

    public function __construct($name, $width)
    {
        parent::__construct($name, $width, $width);
    }


    public function resize($squareObject)
    {
        return parent::resize($squareObject); // TODO: Change the autogenerated stub
    }
}